Update Sync.yml

diff --git a/.github/workflows/Sync.yml b/.github/workflows/Sync.yml
--- a/.github/workflows/Sync.yml
+++ b/.github/workflows/Sync.yml
@@ -1,23 +1,40 @@
-name: Auto Sync and Manual Trigger
+name: Upstream Sync
+
+permissions:
+  contents: write
 
 on:
   schedule:
-    - cron:  '0 0 * * *' # 每天午夜运行
-  workflow_dispatch: # 允许手动触发
+    - cron: "0 0 * * *" # every day
+  workflow_dispatch:
 
 jobs:
-  sync:
+  sync_latest_from_upstream:
+    name: Sync latest commits from upstream repo
     runs-on: ubuntu-latest
+    if: ${{ github.event.repository.fork }}
+
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
+      # Step 1: run a standard checkout action
+      - name: Checkout target repo
+        uses: actions/checkout@v3
 
-    - name: Sync with upstream
-      run: |
-        git remote add upstream https://github.com/hjdhnx/drpy-node.git
-        git fetch upstream
-        git merge upstream/main
+      # Step 2: run the sync action
+      - name: Sync upstream changes
+        id: sync
+        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
+        with:
+          upstream_sync_repo: hjdhnx/drpy-node
+          upstream_sync_branch: main
+          target_sync_branch: main
+          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, no need to set
 
-    - name: Push changes
-      run: |
-        git push origin main
+          # Set test_mode true to run tests instead of the true action!!
+          test_mode: false
+
+      - name: Sync check
+        if: failure()
+        run: |
+          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次。"
+          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
+          exit 1
